name: "Build & Release"
on:
  pull_request:
    branches:
      - main
      - 'feature/*'
  push:
    branches:
      - main
      - 'feature/*'
jobs:  # Telling what jobs we need to happen
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'graalvm'
        java-version: '21'
    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
  build:      # Specify the building name and machine
    permissions: write-all
    name: Build  # you can name the build whatever you want
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
    - uses: subosito/flutter-action@v2
    - name: Install Dependencies
      run: flutter pub get
    - name: Build APK
      run: flutter build apk --release
    - name: Build appBundle
      run: flutter build appbundle
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Releases
        path: build/app/outputs/flutter-apk/app-release.apk
